import bloodDiamond from './images/blood-diamonds.jpg';
import chocolate from './images/chocolate.jpg';
import parasite from './images/parasite.jpg';
import astarisborn from './images/a-star-is-born.jpg';
import notime from './images/no-time-to-die.jpg';
import theoryofeverything from './images/theory-of-everything.jpg';
import matrix from './images/matrix-cover.jpg';

export default function getGallery() {
    return [
      { id: 'bloodDiamonds', title:'Blood Diamonds', image: bloodDiamond, details: 'As civil war rages through 1990s Sierra Leone, two men, a white South African mercenary (Leonardo DiCaprio) and a black Mende fisherman (Djimon Hounsou), become joined in a common quest to recover a rare gem that has the power to transform their lives. With the help of an American journalist (Jennifer Connelly), the men embark on a hazardous trek through rebel territory to achieve their goal' },
      { id: 'chocolate', title:'Chocolate', image: chocolate, details: 'When mysterious Vianne and her child arrive in a tranquil French town in the winter of 1959, no one could have imagined the impact that she and her spirited daughter would have on the community stubbornly rooted in tradition. Within days, she opens an unusual chocolate shop, across the square from the church. Her ability to perceive her customers desires and satisfy them with just the right confection, coaxes the villagers to abandon themselves to temptation -- just as Lent begins.' },
      { id: 'starIsBorn', title:'A Star is Born', image: astarisborn, details: 'Seasoned musician Jackson Maine discovers -- and falls in love with -- struggling artist Ally. She has just about given up on her dream to make it big as a singer until Jackson coaxes her into the spotlight. But even as Ally career takes off, the personal side of their relationship is breaking down, as Jackson fights an ongoing battle with his own internal demons.'},
      { id: 'noTimeToDie', title:'No time to Die', image: notime, details: 'Recruited to rescue a kidnapped scientist, globe-trotting spy James Bond finds himself hot on the trail of a mysterious villain, who is armed with a dangerous new technology.' },
      { id: 'theTheoryOfEverything', title:'The Theory of Everything', image: theoryofeverything, details: 'In the 1960s, Cambridge University student and future physicist Stephen Hawking (Eddie Redmayne) falls in love with fellow collegian Jane Wilde (Felicity Jones). At 21, Hawking learns that he has motor neuron disease. Despite this -- and with Jane at his side -- he begins an ambitious study of time, of which he has very little left, according to his doctor. He and Jane defy terrible odds and break new ground in the fields of medicine and science, achieving more than either could hope to imagine.' },
      { id: 'matrix', title:'Matrix', image: matrix, details: 'Neo (Keanu Reeves) believes that Morpheus (Laurence Fishburne), an elusive figure considered to be the most dangerous man alive, can answer his question -- What is the Matrix? Neo is contacted by Trinity (Carrie-Anne Moss), a beautiful stranger who leads him into an underworld where he meets Morpheus. They fight a brutal battle for their lives against a cadre of viciously intelligent secret agents. It is a truth that could cost Neo something more precious than his life.' },
      { id: 'bloodDiamonds', title:'Blood Diamonds', image: bloodDiamond, details: 'As civil war rages through 1990s Sierra Leone, two men, a white South African mercenary (Leonardo DiCaprio) and a black Mende fisherman (Djimon Hounsou), become joined in a common quest to recover a rare gem that has the power to transform their lives. With the help of an American journalist (Jennifer Connelly), the men embark on a hazardous trek through rebel territory to achieve their goal' },
      { id: 'chocolate', title:'Chocolate', image: chocolate, details: 'When mysterious Vianne and her child arrive in a tranquil French town in the winter of 1959, no one could have imagined the impact that she and her spirited daughter would have on the community stubbornly rooted in tradition. Within days, she opens an unusual chocolate shop, across the square from the church. Her ability to perceive her customers desires and satisfy them with just the right confection, coaxes the villagers to abandon themselves to temptation -- just as Lent begins.' },
      { id: 'starIsBorn', title:'A Star is Born', image: astarisborn, details: 'Seasoned musician Jackson Maine discovers -- and falls in love with -- struggling artist Ally. She has just about given up on her dream to make it big as a singer until Jackson coaxes her into the spotlight. But even as Ally career takes off, the personal side of their relationship is breaking down, as Jackson fights an ongoing battle with his own internal demons.'},
      { id: 'noTimeToDie', title:'No time to Die', image: notime, details: 'Recruited to rescue a kidnapped scientist, globe-trotting spy James Bond finds himself hot on the trail of a mysterious villain, who is armed with a dangerous new technology.' },
      { id: 'theTheoryOfEverything', title:'The Theory of Everything', image: theoryofeverything, details: 'In the 1960s, Cambridge University student and future physicist Stephen Hawking (Eddie Redmayne) falls in love with fellow collegian Jane Wilde (Felicity Jones). At 21, Hawking learns that he has motor neuron disease. Despite this -- and with Jane at his side -- he begins an ambitious study of time, of which he has very little left, according to his doctor. He and Jane defy terrible odds and break new ground in the fields of medicine and science, achieving more than either could hope to imagine.' },
      { id: 'matrix', title:'Matrix', image: matrix, details: 'Neo (Keanu Reeves) believes that Morpheus (Laurence Fishburne), an elusive figure considered to be the most dangerous man alive, can answer his question -- What is the Matrix? Neo is contacted by Trinity (Carrie-Anne Moss), a beautiful stranger who leads him into an underworld where he meets Morpheus. They fight a brutal battle for their lives against a cadre of viciously intelligent secret agents. It is a truth that could cost Neo something more precious than his life.' },
      { id: 'bloodDiamonds', title:'Blood Diamonds', image: bloodDiamond, details: 'As civil war rages through 1990s Sierra Leone, two men, a white South African mercenary (Leonardo DiCaprio) and a black Mende fisherman (Djimon Hounsou), become joined in a common quest to recover a rare gem that has the power to transform their lives. With the help of an American journalist (Jennifer Connelly), the men embark on a hazardous trek through rebel territory to achieve their goal' },
      { id: 'chocolate', title:'Chocolate', image: chocolate, details: 'When mysterious Vianne and her child arrive in a tranquil French town in the winter of 1959, no one could have imagined the impact that she and her spirited daughter would have on the community stubbornly rooted in tradition. Within days, she opens an unusual chocolate shop, across the square from the church. Her ability to perceive her customers desires and satisfy them with just the right confection, coaxes the villagers to abandon themselves to temptation -- just as Lent begins.' },
      { id: 'starIsBorn', title:'A Star is Born', image: astarisborn, details: 'Seasoned musician Jackson Maine discovers -- and falls in love with -- struggling artist Ally. She has just about given up on her dream to make it big as a singer until Jackson coaxes her into the spotlight. But even as Ally career takes off, the personal side of their relationship is breaking down, as Jackson fights an ongoing battle with his own internal demons.'},
      { id: 'noTimeToDie', title:'No time to Die', image: notime, details: 'Recruited to rescue a kidnapped scientist, globe-trotting spy James Bond finds himself hot on the trail of a mysterious villain, who is armed with a dangerous new technology.' },
      { id: 'theTheoryOfEverything', title:'The Theory of Everything', image: theoryofeverything, details: 'In the 1960s, Cambridge University student and future physicist Stephen Hawking (Eddie Redmayne) falls in love with fellow collegian Jane Wilde (Felicity Jones). At 21, Hawking learns that he has motor neuron disease. Despite this -- and with Jane at his side -- he begins an ambitious study of time, of which he has very little left, according to his doctor. He and Jane defy terrible odds and break new ground in the fields of medicine and science, achieving more than either could hope to imagine.' },
      { id: 'matrix', title:'Matrix', image: matrix, details: 'Neo (Keanu Reeves) believes that Morpheus (Laurence Fishburne), an elusive figure considered to be the most dangerous man alive, can answer his question -- What is the Matrix? Neo is contacted by Trinity (Carrie-Anne Moss), a beautiful stranger who leads him into an underworld where he meets Morpheus. They fight a brutal battle for their lives against a cadre of viciously intelligent secret agents. It is a truth that could cost Neo something more precious than his life.' },
      
    ];
}